### ISSUE TITLE
Default Leetcode card not working

### ISSUE THREAD

**Issue by jsmld** [JacobLinCool/LeetCode-Stats-Card#106]
If you change the source to the CN version of LeetCode it seems to work, but not for the default one.

<img width="423" alt="Screenshot 2023-10-29 at 00 05 42" src="https://github.com/JacobLinCool/LeetCode-Stats-Card/assets/21329304/bf50e4c5-7048-4a94-bb3b-4ebc82702132">

**Comment by JacobLinCool** [comment]
Does the problem still exist? I can't reproduce it now.

**Comment by jsmld** [comment]
Sorry it seems to be working again. I will close the issue.
