### ISSUE TITLE
Broken fonts

### ISSUE THREAD

**Issue by CrageJ** [JacobLinCool/LeetCode-Stats-Card#108]
Hi,

I'm trying to use the font [UnifrakturCook](https://fonts.google.com/specimen/UnifrakturCook) for my page, yet the font defaults to Times New Roman as if it were invalid font. The preview is broken both on https://leetcard.jacoblin.cool/ and on GitHub. No combination of themes fixes this. I do not know if other fonts are not working.

![LeetCode Stats](https://leetcard.jacoblin.cool/JacobLinCool?theme=nord&font=UnifrakturCook&ext=heatmap)

Thanks.

**Comment by JacobLinCool** [comment]
Hi @CrageJ, it should be fixed now.

After investigating, I found that [UnifrakturCook](https://fonts.google.com/specimen/UnifrakturCook) does not provide the regular font weight; only bold is available. Therefore, I rebuilt [nano-font](https://github.com/JacobLinCool/nano-font) to include fonts with only bold weight.
