### ISSUE TITLE
Self hosting with docker

### ISSUE THREAD

**Issue by waterfal1** [JacobLinCool/LeetCode-Stats-Card#124]
Hello there! Thank you for providing such an amazing service! I attempted to self-host a Docker image, but unfortunately, I encountered some difficulties. I used [https://hub.docker.com/r/jacoblincool/leetcode-stats-card/tags](url) docker image. I also got the same result after generating my own image from your repository.

I've attached the logs from the web service on Render.com for your review.
![Screenshot from 2024-03-30 14-29-43](https://github.com/JacobLinCool/LeetCode-Stats-Card/assets/73852659/fdbb0914-4244-41a3-8256-0faf7a0b37e7)

**Comment by JacobLinCool** [comment]
Hi @waterfal1 

It requires you to bind in-container path `/worker/cache` to a host directory.

Like this one:

https://github.com/JacobLinCool/LeetCode-Stats-Card/blob/7365d3ee3bec74bcad206a3da0cc9cc71b82b491/docker-compose.yml#L7-L8

Or if you don't need the cache to persist, you can make the directory in your Dockerfile:

```dockerfile
FROM jacoblincool/leetcode-stats-card

RUN mkdir /worker/cache
```

**Comment by waterfal1** [comment]
@JacobLinCool, Thank you! All is good now.
