### ISSUE TITLE
LeetCode stats card image not loading

### ISSUE THREAD

**Issue by ashish0kumar** [JacobLinCool/LeetCode-Stats-Card#145]
The LeetCode Stats Card seems to have stopped working, and the images are not loading as expected. The issue persists across multiple devices and browsers.

The stats card image does not load. Instead, a broken image icon or an empty placeholder is displayed.

### Expected Behavior
The stats card should load the image correctly without any issues.

### Possible Cause
It might be an issue with the image hosting or API that generates the stats card.

### Screenshot
![image](https://github.com/user-attachments/assets/e00a5931-49cf-45b1-9545-5eec997ab4f1)

**Comment by JacobLinCool** [comment]
The new version has been deployed.
It seems that updating the version of leetcode-query fixed the problem. (I'm not sure why the error rate started increasing 36 hours ago.)

<img width="1350" alt="截圖 2024-12-21 晚上9 21 35" src="https://github.com/user-attachments/assets/ffcad159-e451-439f-8a36-e3308761cfa2" />

**Comment by ashish0kumar** [comment]
The contest function is still not working

**Comment by JacobLinCool** [comment]
It should be fixed now. Thanks for your report!
