### ISSUE TITLE
There is no way to hide the border in dark mode

### ISSUE THREAD

**Issue by Mo-Shakib** [JacobLinCool/LeetCode-Stats-Card#26]
Can you please add a feature that will allow users to hide the border in dark mode just adding `&hide_border=true`.

**Comment by JacobLinCool** [comment]
@Mo-Shakib 

You can use `border=0` to change the border width.

**With `border=0`**

![](https://leetcode.card.workers.dev/JacobLinCool?theme=dark&border=0)

**Without `border=0`**

![](https://leetcode.card.workers.dev/JacobLinCool?theme=dark)

**Comment by Mo-Shakib** [comment]
Yep, I found that after opening this issue :3
