### ISSUE TITLE
Image is cached, won't update

### ISSUE THREAD

**Issue by dolanmiu** [JacobLinCool/LeetCode-Stats-Card#28]
It seems the image is cached, so it does not update

You can see the differences here:

# Profile:
https://github.com/dolanmiu

# Image:
https://leetcode.card.workers.dev/dolanmiu?theme=auto&font=baloo&extension=activity

Cached image:

[![LeetCode Stats](https://leetcode.card.workers.dev/dolanmiu?theme=auto&font=baloo&extension=activity)](https://leetcode.com/dolanmiu/)

Code for it:
```md
[![LeetCode Stats](https://leetcode.card.workers.dev/dolanmiu?theme=auto&font=baloo&extension=activity)](https://leetcode.com/dolanmiu/)
```

# LeetCode:
https://leetcode.com/dolanmiu/

**Comment by JacobLinCool** [comment]
@dolanmiu 

I see no difference between the two image.

Both of them are showing 340 for now.

I know GitHub caches all of the images appear in README (including personal profile). But the caching strategy is unknown.

The cache time of the image is set to 1 minute, but I think it is a proper value. I don't know if I should disable that.

**Comment by dolanmiu** [comment]
Sometimes it does not refresh for **days**

I will do a leetcode question sometime in the next few days and report back

How does badges not get cached?

**Comment by JacobLinCool** [comment]
I think if I add `Cache-Control: max-age=0, no-cache` to the response header, then GitHub won't cache it, maybe.

**Comment by dolanmiu** [comment]
Ok look, I have just done a question, it should say 341 (still says 340 at this current time)

**Comment by dolanmiu** [comment]
Ok look, I have just done a question, it should say 341 (still says 340 at this current time)

**Comment by JacobLinCool** [comment]
@dolanmiu 

You can now add `&cache=0` in card's query string to disable the cache.

See #30
