### ISSUE TITLE
CodeFactor link is broken

### ISSUE THREAD

**Issue by lnogueir** [JacobLinCool/LeetCode-Stats-Card#37]
It seems like the CodeFactor badge is broken.

Images below:
<img width="407" alt="Screen Shot 2022-03-15 at 1 26 35 PM" src="https://user-images.githubusercontent.com/48890798/158436096-0afed001-ace8-4293-ac71-2ea82d725563.png">
<img width="556" alt="Screen Shot 2022-03-15 at 1 26 50 PM" src="https://user-images.githubusercontent.com/48890798/158436141-920fdf08-09c5-4c63-b8df-34318f92a8b7.png">

**Comment by JacobLinCool** [comment]
@lnogueir thanks!

It seems that the project somehow disappeared on Codefactor.

I re-added it and the badge should back in a few minutes.

**Comment by lnogueir** [comment]
I can see it now.
