### ISSUE TITLE
site=cn flag no longer working

### ISSUE THREAD

**Issue by STX5** [JacobLinCool/LeetCode-Stats-Card#56]
I used a `https://leetcode.card.workers.dev/MY-LEETCODE-USERNAME?site=cn&theme=default&font=baloo&extension=null`
but recently it's not working

**Comment by JacobLinCool** [comment]
@STX5 

Sorry for the late reply.

I just try the new API, and it seems work as expected now.

`https://leetcard.jacoblin.cool/STX5?site=cn`

![](https://leetcard.jacoblin.cool/STX5?site=cn)

If the problem has been fixed, please feel free to close the issue.

Thanks!

**Comment by STX5** [comment]
Yes it now works just fine!! 
Maybe there was a network issue or a Cloudflare internal issue.
Thanks!
