### ISSUE TITLE
[feature request] add heatmap

### ISSUE THREAD

**Issue by PatternFinder** [JacobLinCool/LeetCode-Stats-Card#62]
could we add a feature for showing the heatmap of daily questions solved too

**Comment by JacobLinCool** [comment]
I agree, that will be helpful.

**Comment by JacobLinCool** [comment]
@PatternFinder 

You can now use `?ext=heatmap` to enable heatmap.

![](https://leetcard.jacoblin.cool/jacoblincool?ext=heatmap)

PR: #64

**Comment by PatternFinder** [comment]
that's awesome bro!
