### ISSUE TITLE
service is totally down for leetcode.cn

### ISSUE THREAD

**Issue by wuuconix** [JacobLinCool/LeetCode-Stats-Card#78]
https://leetcard.jacoblin.cool/wuuconix?site=cn

I tried many times in many devices and in different networks. But it always return Error 1101.
Does something changed in leetcard.cn?
![image](https://user-images.githubusercontent.com/80732538/214022063-a6fecf56-aa96-41e4-816f-53faf944e9b2.png)

**Comment by JacobLinCool** [comment]
I have identified an issue with the upstream library regarding the method for obtaining CSRF tokens. (https://github.com/JacobLinCool/LeetCode-Query/issues/55)

I am currently working to resolve the issue and will keep you informed of any updates. 

Thank you for bringing this to my attention.

**Comment by JacobLinCool** [comment]
https://leetcard.jacoblin.cool/wuuconix?site=cn should now function as intended.

If you encounter any further issues, feel free to open a new one. Thanks!
