### ISSUE TITLE
Custom option to use our own theme

### ISSUE THREAD

**Issue by RedHeadphone** [JacobLinCool/LeetCode-Stats-Card#81]
Basically custom options which can be provided by query params which is used for theme.
Like [this](https://github.com/anuraghazra/github-readme-stats#customization)

**Comment by JacobLinCool** [comment]
You can utilize external stylesheets, such as [this one on Gist](https://gist.github.com/JacobLinCool/4ba186dcd038b6d0fc4d69ab8480baba), to design your card. 

This approach provides greater flexibility compared to utilizing querystring options.

The card by applying the above stylesheet:
![](https://leetcard.jacoblin.cool/JacobLinCool?sheets=https://gist.githubusercontent.com/JacobLinCool/4ba186dcd038b6d0fc4d69ab8480baba/raw/fd9a589398248bef3ed351374d07c300eb3abdb6/example.css)

```
https://leetcard.jacoblin.cool/JacobLinCool?sheets=https://gist.githubusercontent.com/JacobLinCool/4ba186dcd038b6d0fc4d69ab8480baba/raw/fd9a589398248bef3ed351374d07c300eb3abdb6/example.css
```

**Comment by RedHeadphone** [comment]
woah nice approach, but in future will you be down to add query parameters?
