### ISSUE TITLE
Center the stats box

### ISSUE THREAD

**Issue by Zarak-Shah-ji** [JacobLinCool/LeetCode-Stats-Card#89]
I'm trying to do basic centering of the stat box but when I try to use  `<p align="center">` or  div tag the box disappears and only the link is seen on my github readme
![Screenshot (105)](https://user-images.githubusercontent.com/47606946/232927321-edd26372-783f-41d0-96cf-10a978448715.png)

**Comment by JacobLinCool** [comment]
You can use inline HTML to center the image:

```html
<p align="center">
    <img src="https://leetcard.jacoblin.cool/JacobLinCool" />
</p>
```

<p align="center">
    <img src="https://leetcard.jacoblin.cool/JacobLinCool" />
</p>

**Comment by Zarak-Shah-ji** [comment]
Worked! thanks
