### ISSUE TITLE
Is LeetCard down?

### ISSUE THREAD

**Issue by aryanjain28** [JacobLinCool/LeetCode-Stats-Card#93]
06/07/2023.

<img width="1025" alt="image" src="https://github.com/JacobLinCool/LeetCode-Stats-Card/assets/42910418/3eada602-e405-4e37-ba62-40a8842c94db">

Seems like a broken pipeline [CloudFare].

**Comment by JacobLinCool** [comment]
It seems to be working fine now.

![](https://leetcard.jacoblin.cool/JacobLinCool?theme=unicorn&font=Baloo%202)

However, I noticed a peak in the error rate around 30 minutes ago, accompanied by several "client disconnected" events, which were unusual.

<img width="1063" alt="截圖 2023-06-08 上午12 42 43" src="https://github.com/JacobLinCool/LeetCode-Stats-Card/assets/28478594/9775d809-9014-45fd-af39-f2f3473b1606">

Please let me know if the issue still persists.
